pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('employee-management-app') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Angular App') {
            steps {
                dir('employee-management-app') {
                    bat 'npm run build'
                }
            }
        }
        stage('Lint') {
    steps {
        dir('employee-management-app') {
            bat 'npm run lint'
        }
    }
    stage('Test') {
    steps {
        dir('employee-management-app') {
            bat 'npm test -- --watch=false'
        }
    }
}
}
    }

    post {
    success {
        archiveArtifacts artifacts: 'employee-management-app/dist/**/*'
        echo 'Build completed successfully'
    }

    failure {
        echo 'Build failed'
    }
}
}